import { Router } from "express";
import passport from "../middlewares/passport.js";
import validator from "../middlewares/validator.js";
import { readCategory, readSubCategory } from "../controllers/categories/get.js";
import destroy from "../controllers/categories/delete.js";
import nameAlreadyExist from "../middlewares/userNameAlreadyExist.js";
import { createSubCategory, createCategory } from "../controllers/categories/post.js";
import { categorySchema, categorySchemaUpdate, subCategorySchema } from "../schemas/categories.js";
let router = Router();
router.get("/:user_id", readCategory);
router.get("/sub/:user_id", readSubCategory);
router.post("/:user_id", passport.authenticate("jwt", { session: false }), validator(categorySchema), createCategory);
router.post("/sub/:user_id", passport.authenticate("jwt", { session: false }), nameAlreadyExist, validator(subCategorySchema), createSubCategory);
router.delete("/:id/:user_id", passport.authenticate("jwt", { session: false }), validator(categorySchemaUpdate), destroy);
export default router;